export const playerTokens = {
  barHeight: 92,
  minBarHeight: 74,
  floatingBottom: 16,
  minTrackColumn: 260,
  maxTrackColumn: 320,
  minCoreColumn: 360,
  minMetaColumn: 210,
  maxMetaColumn: 280,
  gapMin: 14,
  gapViewport: 2,
  gapMax: 24,
  marginInlineMin: 18,
  marginInlineViewport: 2.5,
  marginInlineMax: 30,
  paddingBlock: 10,
  paddingInline: 16,
  radius: 24,
  compactTrackColumn: 220,
  compactTrackColumnMax: 280,
  compactCoreColumn: 280,
  compactGap: 12,
  controlCoreGap: 7,
  controlButtonGap: 12,
  controlSize: 30,
  controlPrimarySize: 38,
  iconSize: 17,
  iconPrimarySize: 18,
  timebarMaxWidth: 480,
  timebarSideColumn: 36,
  timebarTrackMin: 170,
  timebarGap: 9,
  timebarFontSize: 10.5,
  progressHeight: 3,
  trackInfoArtSize: 50,
  trackInfoGap: 11,
  trackInfoArtRadius: 13,
  trackInfoTitleFontSize: 13,
  trackInfoArtistTopSpace: 3,
  trackInfoArtistFontSize: 12,
  trackInfoActionsGap: 4,
  trackInfoActionSize: 26,
} as const

export type PlayerTokens = typeof playerTokens
