export const premiumLocalHomeCopy = {
  ariaLabel: 'premiumLocal 首页体验',
  featureStackAriaLabel: '本地资料库精选卡片',
  heroAriaLabel: '继续聆听精选专辑',
  moreAriaLabel: '更多操作',
  playAlbumAriaLabel: '播放 {album}',
  showAllLabel: '查看全部',
  spotlightAriaLabel: '首页焦点内容',
  header: {
    actionsAriaLabel: '首页顶部操作',
    description: '从本地资料库继续播放，安静发现最近加入的专辑。',
    eyebrow: 'Kivo Music',
    searchAriaLabel: '搜索本地资料库',
    searchPlaceholder: '搜索专辑、艺人、歌曲',
    statusAriaLabel: '本地资料库状态',
    statusLabel: '本地资料库',
    statusValue: '1,286 首 · 无损就绪',
    title: '欢迎回来',
  },
  player: {
    ariaLabel: 'premiumLocal 播放器视觉面板',
    controlsAriaLabel: '播放器视觉控制',
    favoriteAriaLabel: '收藏当前曲目',
    metaAriaLabel: '播放器状态',
    nextAriaLabel: '下一首',
    pauseAriaLabel: '暂停',
    previousAriaLabel: '上一首',
    progressAriaLabel: '播放进度',
    queueAriaLabel: '打开队列',
    volumeAriaLabel: '音量',
  },
  shelves: {
    recentlyAdded: { eyebrow: '最近加入', title: '资料库新加入。' },
    recentlyPlayed: { eyebrow: '最近播放', title: '继续聆听。' },
  },
} as const
