export const premiumLocalHomeCopy = {
  ariaLabel: 'premiumLocal 首页体验',
  featureStackAriaLabel: '本地资料库精选卡片',
  heroAriaLabel: '继续聆听精选专辑',
  moreAriaLabel: '更多操作',
  playAlbumAriaLabel: '播放 {album}',
  showAllLabel: '查看全部',
  spotlightAriaLabel: '首页焦点内容',
  header: {
    description: '继续播放你的本地收藏，安静发现最近加入的专辑。',
    eyebrow: 'Kivo Music',
    title: '欢迎回来',
  },
  player: {
    ariaLabel: 'premiumLocal 播放器视觉面板',
    controlsAriaLabel: '播放器视觉控制',
    favoriteAriaLabel: '收藏当前曲目',
    metaAriaLabel: '播放器状态',
    nextAriaLabel: '下一首',
    pauseAriaLabel: '暂停',
    previousAriaLabel: '上一首',
    progressAriaLabel: '播放进度',
    queueAriaLabel: '打开队列',
    volumeAriaLabel: '音量',
  },
  shelves: {
    recentlyAdded: { eyebrow: '最近加入', title: '资料库新加入。' },
    recentlyPlayed: { eyebrow: '最近播放', title: '继续聆听。' },
  },
} as const
