pub(crate) const MAX_RENDER_RING_BUFFER_BOUNDARY_ITERATIONS: u32 = 3;
pub(crate) const MAX_RENDER_RING_BUFFER_BOUNDARY_FRAMES_PER_WRITE: u32 = 128;
pub(crate) const MAX_SYNTHETIC_ZERO_SEED_FRAMES: u32 = 128;
