import type { CSSProperties } from 'react'
import { playerTokens } from '../../shared/design'

type PlayerBarStyle = CSSProperties & Record<`--${string}`, string>

export const playerBarStyle: PlayerBarStyle = {
  '--km-player-min-bar-height': `${playerTokens.minBarHeight}px`,
  '--km-player-floating-bottom': `${playerTokens.floatingBottom}px`,
  '--km-player-track-min': `${playerTokens.minTrackColumn}px`,
  '--km-player-track-max': `${playerTokens.maxTrackColumn}px`,
  '--km-player-core-min': `${playerTokens.minCoreColumn}px`,
  '--km-player-meta-min': `${playerTokens.minMetaColumn}px`,
  '--km-player-meta-max': `${playerTokens.maxMetaColumn}px`,
  '--km-player-gap-min': `${playerTokens.gapMin}px`,
  '--km-player-gap-vw': `${playerTokens.gapViewport}vw`,
  '--km-player-gap-max': `${playerTokens.gapMax}px`,
  '--km-player-margin-inline-min': `${playerTokens.marginInlineMin}px`,
  '--km-player-margin-inline-vw': `${playerTokens.marginInlineViewport}vw`,
  '--km-player-margin-inline-max': `${playerTokens.marginInlineMax}px`,
  '--km-player-padding-block': `${playerTokens.paddingBlock}px`,
  '--km-player-padding-inline': `${playerTokens.paddingInline}px`,
  '--km-player-radius': `${playerTokens.radius}px`,
  '--km-player-compact-track-min': `${playerTokens.compactTrackColumn}px`,
  '--km-player-compact-track-max': `${playerTokens.compactTrackColumnMax}px`,
  '--km-player-compact-core-min': `${playerTokens.compactCoreColumn}px`,
  '--km-player-compact-gap': `${playerTokens.compactGap}px`,
  '--km-player-control-core-gap': `${playerTokens.controlCoreGap}px`,
  '--km-player-control-button-gap': `${playerTokens.controlButtonGap}px`,
  '--km-player-control-size': `${playerTokens.controlSize}px`,
  '--km-player-control-primary-size': `${playerTokens.controlPrimarySize}px`,
  '--km-player-icon-size': `${playerTokens.iconSize}px`,
  '--km-player-icon-primary-size': `${playerTokens.iconPrimarySize}px`,
  '--km-player-timebar-max': `${playerTokens.timebarMaxWidth}px`,
  '--km-player-timebar-side': `${playerTokens.timebarSideColumn}px`,
  '--km-player-timebar-track-min': `${playerTokens.timebarTrackMin}px`,
  '--km-player-timebar-gap': `${playerTokens.timebarGap}px`,
  '--km-player-timebar-font-size': `${playerTokens.timebarFontSize}px`,
  '--km-player-progress-height': `${playerTokens.progressHeight}px`,
  '--km-player-track-info-art': `${playerTokens.trackInfoArtSize}px`,
  '--km-player-track-info-gap': `${playerTokens.trackInfoGap}px`,
  '--km-player-track-info-art-radius': `${playerTokens.trackInfoArtRadius}px`,
  '--km-player-track-info-title-size': `${playerTokens.trackInfoTitleFontSize}px`,
  '--km-player-track-info-artist-top': `${playerTokens.trackInfoArtistTopSpace}px`,
  '--km-player-track-info-artist-size': `${playerTokens.trackInfoArtistFontSize}px`,
  '--km-player-track-info-actions-gap': `${playerTokens.trackInfoActionsGap}px`,
  '--km-player-track-info-action-size': `${playerTokens.trackInfoActionSize}px`,
}
