import { albumShelfTokens } from './tokens/albumShelfTokens'
import { listenNowLayoutTokens } from './tokens/listenNowLayoutTokens'
import { shelfHeadTokens } from './tokens/shelfHeadTokens'
import { topPicksTokens } from './tokens/topPicksTokens'

export const listenNowTokens = {
  sectionBottomSpace: listenNowLayoutTokens.sectionBottomSpace,
  headBottomSpace: listenNowLayoutTokens.headBottomSpace,
  topPicksGap: topPicksTokens.gap,
  topPicksFeaturedMinWidth: topPicksTokens.featuredMinWidth,
  topPicksCardMinWidth: topPicksTokens.cardMinWidth,
  topPickRadius: topPicksTokens.cardRadius,
  topPickMinHeight: topPicksTokens.cardMinHeight,
  topPickMaxHeight: topPicksTokens.cardMaxHeight,
  topPickFeaturedMinHeight: topPicksTokens.featuredMinHeight,
  topPickFeaturedMaxHeight: topPicksTokens.featuredMaxHeight,
  topPickOverlayHighlight: topPicksTokens.overlayHighlight,
  topPickOverlaySide: topPicksTokens.overlaySide,
  topPickOverlayBottom: topPicksTokens.overlayBottom,
  topPickCopyTop: topPicksTokens.copyTop,
  topPickCopyInline: topPicksTokens.copyInline,
  topPickCopyBottom: topPicksTokens.copyBottom,
  topPickTextColor: topPicksTokens.textColor,
  topPickMutedTextColor: topPicksTokens.mutedTextColor,
  topPickEyebrowFontSize: topPicksTokens.eyebrowFontSize,
  topPickEyebrowWeight: topPicksTokens.eyebrowWeight,
  topPickEyebrowTracking: topPicksTokens.eyebrowTracking,
  topPickTitleTopSpace: topPicksTokens.titleTopSpace,
  topPickTitleMinFontSize: topPicksTokens.titleMinFontSize,
  topPickTitleMaxFontSize: topPicksTokens.titleMaxFontSize,
  topPickTitleTracking: topPicksTokens.titleTracking,
  topPickDescriptionTopSpace: topPicksTokens.descriptionTopSpace,
  topPickDescriptionFontSize: topPicksTokens.descriptionFontSize,
  topPickPlayRight: topPicksTokens.playRight,
  topPickPlayBottom: topPicksTokens.playBottom,
  topPickPlaySize: topPicksTokens.playSize,
  topPickPlayColor: topPicksTokens.playColor,
  topPickPlayBackground: topPicksTokens.playBackground,
  topPickPlayShadow: topPicksTokens.playShadow,
  shelfHeadGap: shelfHeadTokens.gap,
  shelfHeadBottomSpace: shelfHeadTokens.bottomSpace,
  shelfEyebrowFontSize: shelfHeadTokens.eyebrowFontSize,
  shelfEyebrowWeight: shelfHeadTokens.eyebrowWeight,
  shelfEyebrowTracking: shelfHeadTokens.eyebrowTracking,
  shelfTitleTopSpace: shelfHeadTokens.titleTopSpace,
  shelfTitleFontSize: shelfHeadTokens.titleFontSize,
  shelfTitleTracking: shelfHeadTokens.titleTracking,
  shelfButtonPaddingY: shelfHeadTokens.buttonPaddingY,
  shelfButtonPaddingX: shelfHeadTokens.buttonPaddingX,
  darkShelfButtonBackground: shelfHeadTokens.darkButtonBackground,
  albumGridGap: albumShelfTokens.gridGap,
  albumShelfLastBottomSpace: albumShelfTokens.shelfLastBottomSpace,
  albumCardMinWidth: albumShelfTokens.cardMinWidth,
  albumCardMaxWidth: albumShelfTokens.cardMaxWidth,
  albumCardRadius: albumShelfTokens.cardRadius,
  albumCardTransitionMs: albumShelfTokens.cardTransitionMs,
  albumCardHoverLift: albumShelfTokens.cardHoverLift,
  albumCardActiveLift: albumShelfTokens.cardActiveLift,
  albumCardActiveScale: albumShelfTokens.cardActiveScale,
  albumCardActiveOpacity: albumShelfTokens.cardActiveOpacity,
  albumArtRadius: albumShelfTokens.artRadius,
  albumArtBottomSpace: albumShelfTokens.artBottomSpace,
  albumTitleFontSize: albumShelfTokens.titleFontSize,
  albumTitleWeight: albumShelfTokens.titleWeight,
  albumTitleTracking: albumShelfTokens.titleTracking,
  albumArtistTopSpace: albumShelfTokens.artistTopSpace,
  albumArtistFontSize: albumShelfTokens.artistFontSize,
  albumQualityTopSpace: albumShelfTokens.qualityTopSpace,
  albumQualityFontSize: albumShelfTokens.qualityFontSize,
} as const

export type ListenNowTokens = typeof listenNowTokens
