export const listenNowTokens = {
  sectionBottomSpace: 20,
  headBottomSpace: 12,
  topPicksGap: 16,
  topPicksFeaturedMinWidth: 280,
  topPicksCardMinWidth: 220,
  topPickRadius: 16,
  topPickMinHeight: 136,
  topPickMaxHeight: 168,
  topPickFeaturedMinHeight: 146,
  topPickFeaturedMaxHeight: 178,
  topPickCopyTop: 16,
  topPickCopyInline: 18,
  topPickCopyBottom: 20,
  topPickEyebrowFontSize: 10,
  topPickTitleMinFontSize: 20,
  topPickTitleMaxFontSize: 28,
  topPickDescriptionTopSpace: 7,
  topPickDescriptionFontSize: 11,
  topPickPlayRight: 16,
  topPickPlayBottom: 18,
  topPickPlaySize: 36,
  shelfHeadGap: 10,
  shelfHeadBottomSpace: 10,
  shelfButtonPaddingY: 8,
  shelfButtonPaddingX: 14,
  albumGridGap: 16,
  albumShelfLastBottomSpace: 182,
  albumCardMinWidth: 116,
  albumCardMaxWidth: 132,
  albumCardRadius: 13,
  albumArtRadius: 11,
  albumArtBottomSpace: 8,
  albumTitleFontSize: 12,
  albumArtistTopSpace: 2,
  albumArtistFontSize: 12,
  albumQualityTopSpace: 3,
  albumQualityFontSize: 11,
} as const

export type ListenNowTokens = typeof listenNowTokens
