import type { CSSProperties } from 'react'
import { listenNowTokens } from './listenNowTokens'

type ListenNowStyle = CSSProperties & Record<`--${string}`, string>

export const listenNowStyle: ListenNowStyle = {
  '--km-listen-section-bottom': `${listenNowTokens.sectionBottomSpace}px`,
  '--km-listen-head-bottom': `${listenNowTokens.headBottomSpace}px`,
  '--km-listen-top-picks-gap': `${listenNowTokens.topPicksGap}px`,
  '--km-listen-top-picks-featured-min': `${listenNowTokens.topPicksFeaturedMinWidth}px`,
  '--km-listen-top-picks-card-min': `${listenNowTokens.topPicksCardMinWidth}px`,
  '--km-listen-top-pick-radius': `${listenNowTokens.topPickRadius}px`,
  '--km-listen-top-pick-min-height': `${listenNowTokens.topPickMinHeight}px`,
  '--km-listen-top-pick-max-height': `${listenNowTokens.topPickMaxHeight}px`,
  '--km-listen-top-pick-featured-min-height': `${listenNowTokens.topPickFeaturedMinHeight}px`,
  '--km-listen-top-pick-featured-max-height': `${listenNowTokens.topPickFeaturedMaxHeight}px`,
  '--km-listen-top-pick-overlay-highlight': listenNowTokens.topPickOverlayHighlight,
  '--km-listen-top-pick-overlay-side': listenNowTokens.topPickOverlaySide,
  '--km-listen-top-pick-overlay-bottom': listenNowTokens.topPickOverlayBottom,
  '--km-listen-top-pick-copy-top': `${listenNowTokens.topPickCopyTop}px`,
  '--km-listen-top-pick-copy-inline': `${listenNowTokens.topPickCopyInline}px`,
  '--km-listen-top-pick-copy-bottom': `${listenNowTokens.topPickCopyBottom}px`,
  '--km-listen-top-pick-text-color': listenNowTokens.topPickTextColor,
  '--km-listen-top-pick-muted-text-color': listenNowTokens.topPickMutedTextColor,
  '--km-listen-top-pick-eyebrow-size': `${listenNowTokens.topPickEyebrowFontSize}px`,
  '--km-listen-top-pick-eyebrow-weight': String(listenNowTokens.topPickEyebrowWeight),
  '--km-listen-top-pick-eyebrow-letter-spacing': listenNowTokens.topPickEyebrowTracking,
  '--km-listen-top-pick-title-top': `${listenNowTokens.topPickTitleTopSpace}px`,
  '--km-listen-top-pick-title-min-size': `${listenNowTokens.topPickTitleMinFontSize}px`,
  '--km-listen-top-pick-title-max-size': `${listenNowTokens.topPickTitleMaxFontSize}px`,
  '--km-listen-top-pick-title-letter-spacing': listenNowTokens.topPickTitleTracking,
  '--km-listen-top-pick-description-top': `${listenNowTokens.topPickDescriptionTopSpace}px`,
  '--km-listen-top-pick-description-size': `${listenNowTokens.topPickDescriptionFontSize}px`,
  '--km-listen-top-pick-play-right': `${listenNowTokens.topPickPlayRight}px`,
  '--km-listen-top-pick-play-bottom': `${listenNowTokens.topPickPlayBottom}px`,
  '--km-listen-top-pick-play-size': `${listenNowTokens.topPickPlaySize}px`,
  '--km-listen-top-pick-play-color': listenNowTokens.topPickPlayColor,
  '--km-listen-top-pick-play-bg': listenNowTokens.topPickPlayBackground,
  '--km-listen-top-pick-play-shadow': listenNowTokens.topPickPlayShadow,
  '--km-listen-shelf-head-gap': `${listenNowTokens.shelfHeadGap}px`,
  '--km-listen-shelf-head-bottom': `${listenNowTokens.shelfHeadBottomSpace}px`,
  '--km-listen-shelf-eyebrow-size': `${listenNowTokens.shelfEyebrowFontSize}px`,
  '--km-listen-shelf-eyebrow-weight': String(listenNowTokens.shelfEyebrowWeight),
  '--km-listen-shelf-eyebrow-letter-spacing': listenNowTokens.shelfEyebrowTracking,
  '--km-listen-shelf-title-top': `${listenNowTokens.shelfTitleTopSpace}px`,
  '--km-listen-shelf-title-size': `${listenNowTokens.shelfTitleFontSize}px`,
  '--km-listen-shelf-title-letter-spacing': listenNowTokens.shelfTitleTracking,
  '--km-listen-shelf-button-y': `${listenNowTokens.shelfButtonPaddingY}px`,
  '--km-listen-shelf-button-x': `${listenNowTokens.shelfButtonPaddingX}px`,
  '--km-listen-dark-shelf-button-bg': listenNowTokens.darkShelfButtonBackground,
  '--km-listen-album-grid-gap': `${listenNowTokens.albumGridGap}px`,
  '--km-listen-album-shelf-last-bottom': `${listenNowTokens.albumShelfLastBottomSpace}px`,
  '--km-listen-album-card-min': `${listenNowTokens.albumCardMinWidth}px`,
  '--km-listen-album-card-max': `${listenNowTokens.albumCardMaxWidth}px`,
  '--km-listen-album-card-radius': `${listenNowTokens.albumCardRadius}px`,
  '--km-listen-album-art-radius': `${listenNowTokens.albumArtRadius}px`,
  '--km-listen-album-art-bottom': `${listenNowTokens.albumArtBottomSpace}px`,
  '--km-listen-album-title-size': `${listenNowTokens.albumTitleFontSize}px`,
  '--km-listen-album-artist-top': `${listenNowTokens.albumArtistTopSpace}px`,
  '--km-listen-album-artist-size': `${listenNowTokens.albumArtistFontSize}px`,
  '--km-listen-album-quality-top': `${listenNowTokens.albumQualityTopSpace}px`,
  '--km-listen-album-quality-size': `${listenNowTokens.albumQualityFontSize}px`,
}
