export const topBarTokens = {
  minHeight: 72,
  titleMinColumn: 480,
  searchMinColumn: 240,
  searchMaxColumn: 360,
  compactTitleMinColumn: 360,
  compactSearchMinColumn: 220,
  compactSearchMaxColumn: 300,
  gap: 16,
  paddingTop: 20,
  paddingBottom: 12,
  titleEyebrowFontSize: 11,
  titleTopSpace: 3,
  titleMaxWidthCh: 18,
  titleMinFontSize: 30,
  titleMaxFontSize: 42,
  compactTitleMaxWidthCh: 16,
  compactTitleFontSize: 32,
  searchGap: 9,
  searchPaddingBlock: 9,
  searchPaddingInline: 13,
  searchLabelFontSize: 10,
  statusPaddingBlock: 9,
  statusPaddingInline: 12,
  statusRadius: 14,
  statusLabelFontSize: 11,
  statusValueTopSpace: 2,
  statusValueFontSize: 12,
  statusDotSize: 6,
  statusDotGap: 7,
} as const

export type TopBarTokens = typeof topBarTokens
